language: java
jdk:
  - openjdk14
addons:
  sonarcloud:
    organization: lexie93
    token: $SONAR_TOKEN
script:
  - mvn install sonar:sonar -Pcoverage -Dsonar.projectKey=Lexie93_bookkeeper -Dsonar.language=java -Dsonar.java.binaries=. -Dmaven.javadoc.skip=true

